<a href="https://colab.research.google.com/github/weoruhsyfbxjc/bigdata/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([1, 2, 3], dtype=int)

In [2]:
a

array([1, 2, 3])

In [3]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [4]:
a.data

In [19]:
np.array([1, 2, 3])

array([1, 2, 3])

네, 파이썬을 공부하시는 분들을 위해 이 오류를 좀 더 자세히 설명해 드릴게요.

TypeError: array() takes from 1 to 2 positional arguments but 3 were given 오류 메시지는 np.array() 함수를 호출할 때 전달된 인수의 개수가 함수가 예상하는 개수와 다르다는 것을 의미합니다.

파이썬에서 함수를 호출할 때 괄호 () 안에 값을 넣어주는데, 이 값들을 '인수(arguments)'라고 합니다. np.array() 함수는 기본적으로 두 가지 방식의 인수를 받습니다.

배열처럼 만들고 싶은 하나의 객체(예: 리스트, 튜플)를 인수로 받는 경우: 이 경우는 가장 흔하게 사용되며, [1, 2, 3]와 같이 하나의 파이썬 리스트를 np.array() 함수에 전달하여 NumPy 배열을 만듭니다. 이때 [1, 2, 3] 전체가 함수의 '첫 번째' 인수가 됩니다. 예시: np.array([1, 2, 3])

첫 번째 객체와 함께 dtype과 같은 추가 옵션을 받는 경우: 예를 들어 np.array([1, 2, 3], dtype=int)와 같이 배열의 데이터 타입을 지정할 수 있습니다. 이 경우 [1, 2, 3]이 첫 번째 인수가 되고, dtype=int는 '두 번째' 인수로 처리됩니다. 이때 dtype은 키워드 인수(keyword argument)라고 부르며, 이름과 함께 전달됩니다.

원래 코드 np.array(1, 2, 3)에서는 1, 2, 3을 각각 별개의 인수로 함수에 전달했습니다. np.array() 함수는 이것을 세 개의 독립적인 인수로 인식했고, array() 함수가 예상하는 인수의 개수는 최대 두 개였기 때문에 3개 인수가 주어졌다(3 were given)는 오류가 발생한 것입니다.

해결책으로 np.array([1, 2, 3])와 같이 1, 2, 3을 대괄호 []로 묶어 파이썬 '리스트'로 만들면, 이 리스트 자체가 np.array() 함수의 첫 번째(그리고 유일한) 인수로 전달됩니다. 이렇게 하면 함수는 하나의 객체(리스트)를 받아서 그 내용으로 NumPy 배열을 올바르게 생성할 수 있습니다.


In [6]:
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [7]:
lang = np.array(['가나다', '라마다', '사아자'], dtype='<U3')
lang

array(['가나다', '라마다', '사아자'], dtype='<U3')

In [8]:
a = np.array((1, 2, 3), dtype=float)
a

array([1., 2., 3.])

In [9]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])

In [10]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [11]:
a.dtype

dtype('float64')

In [12]:
np.zeros((5,), dtype=int)


array([0, 0, 0, 0, 0])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [15]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [16]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [17]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [18]:
np.full([4, 3], fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [25]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a


array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [28]:
a.sum()

np.int64(46)

In [29]:
print(a.sum())

46


In [ ]:
import numpy as np
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a[0]

np.int64(0)

In [ ]:
a[3]

np.int64(9)

In [ ]:
int(a[3])

9

In [ ]:
int(a[-2])

64

In [ ]:
a[1:4]

array([1, 4, 9])

In [ ]:
a[-5:-1]

array([25, 36, 49, 64])

In [ ]:
a[8:2:-2]

array([64, 36, 16])

In [ ]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
?

In [ ]:
a.reshape(3, 2, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b.reshape(3,2,4)
b

NameError: name 'b' is not defined

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[:, 1]


array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

앞에는 전체. 그 전체에서 0, 다음 첫번째 행

In [ ]:
a[:, 1, 1]

array([ 5, 17])

그 중에서 또 0 다음 두번째

In [ ]:
a[:,:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

모든 축 행에서 두번째 아유씨 모르겠다 어려운데
# 여기 다시봐라

In [ ]:
a[:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[...]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.arange(1, 7).reshape(2, 3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a = np.arange(1, 7).reshape(2, 3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

브로드캐스팅 과제야 해야해

## 고급 색인

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
int(x[1])

1

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[[1]]

array([1])

In [ ]:
x[[1, 1, 2, 5]]

array([1, 1, 2, 5])

In [ ]:
x[[1, 1, 2, 5, -1, -2, 5]]

array([1, 1, 2, 5, 9, 8, 5])

In [ ]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
x[[5, 6]]

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[[6,5]]

array([[48, 49, 50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[0,0]

np.int64(0)

In [ ]:
int(x[0,0])

0

In [ ]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [ ]:
x[0, 1]

np.int64(1)

In [ ]:
x[[0], [1]]

array([1])

In [ ]:
x[[0,-1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [ ]:
x[0, 1]

In [ ]:
x[ :, [2,1] ]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [ ]:
x[ [1, 3] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [1], [2] ]

array([10])

In [ ]:
x[ [1,3], [2,2] ]

array([10, 26])

In [ ]:
x[ [1,3], [2,2,3] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [ ]:
x[ [1,3], [2] ]

array([10, 26])

In [ ]:
x[ [1,3], 2 ]

array([10, 26])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0, 2, 4], 1 ]

array([ 1, 17, 33])

In [ ]:
x[ [0, 2, 4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[ [2, 3] ]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[ [2, 3, 4] ]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[ np.arange(2, -4)]

array([], shape=(0, 8), dtype=int64)

In [ ]:
a[ np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[ np.arange(2, 4) ][: , [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [ ]:
a[ np.arange(2, 4) ][: , [1, 0]]

array([[17, 16],
       [25, 24]])

In [ ]:
np.arange(-1, -8, -1)

array([-1, -2, -3, -4, -5, -6, -7])

In [ ]:
a[ np.arange(2, 4) ][: , np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25]])

In [ ]:
a[ np.arange(2, 5) ][: , np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])