<a href="https://colab.research.google.com/github/weoruhsyfbxjc/bigdata/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [2]:
a[0]

np.int64(0)

In [3]:
a[3]

np.int64(9)

In [4]:
int(a[3])

9

In [5]:
int(a[-2])

64

In [6]:
a[1:4]

array([1, 4, 9])

In [7]:
a[-5:-1]

array([25, 36, 49, 64])

In [8]:
a[8:2:-2]

array([64, 36, 16])

In [9]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
?

In [15]:
a.reshape(3, 2, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
b.reshape(3,2,4)
b

NameError: name 'b' is not defined

In [17]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a[:, 1]


array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

앞에는 전체. 그 전체에서 0, 다음 첫번째 행

In [26]:
a[:, 1, 1]

array([ 5, 17])

그 중에서 또 0 다음 두번째

In [27]:
a[:,:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

모든 축 행에서 두번째 아유씨 모르겠다 어려운데
# 여기 다시봐라

In [29]:
a[:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
a[...]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [35]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a = np.arange(1, 7).reshape(2, 3)

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
a = np.arange(1, 7).reshape(2, 3)

In [43]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

브로드캐스팅 과제야 해야해

## 고급 색인

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
int(x[1])

1

In [49]:
x[:5]

array([0, 1, 2, 3, 4])

In [50]:
x[[1]]

array([1])

In [51]:
x[[1, 1, 2, 5]]

array([1, 1, 2, 5])

In [52]:
x[[1, 1, 2, 5, -1, -2, 5]]

array([1, 1, 2, 5, 9, 8, 5])

In [53]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [54]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [55]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [56]:
x[[5, 6]]

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [57]:
x[[6,5]]

array([[48, 49, 50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [58]:
x[0,1]

np.int64(1)

In [59]:
x[0,0]

np.int64(0)

In [60]:
int(x[0,0])

0

In [61]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [62]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [63]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [65]:
x[0, 1]

np.int64(1)

In [66]:
x[[0], [1]]

array([1])

In [67]:
x[[0,-1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [68]:
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [ ]:
x[0, 1]

In [71]:
x[ :, [2,1] ]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [72]:
x[ [1, 3] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [73]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [74]:
x[ [1], [2] ]

array([10])

In [75]:
x[ [1,3], [2,2] ]

array([10, 26])

In [76]:
x[ [1,3], [2,2,3] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [77]:
x[ [1,3], [2] ]

array([10, 26])

In [78]:
x[ [1,3], 2 ]

array([10, 26])

In [79]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [80]:
x[ [0, 2, 4], 1 ]

array([ 1, 17, 33])

In [81]:
x[ [0, 2, 4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [82]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [83]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [84]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [85]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [86]:
a[ [2, 3] ]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [87]:
a[ [2, 3, 4] ]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [88]:
a[ np.arange(2, -4)]

array([], shape=(0, 8), dtype=int64)

In [90]:
a[ np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [91]:
a[ np.arange(2, 4) ][: , [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [92]:
a[ np.arange(2, 4) ][: , [1, 0]]

array([[17, 16],
       [25, 24]])

In [93]:
np.arange(-1, -8, -1)

array([-1, -2, -3, -4, -5, -6, -7])

In [94]:
a[ np.arange(2, 4) ][: , np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25]])

In [96]:
a[ np.arange(2, 5) ][: , np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])