<a href="https://colab.research.google.com/github/weoruhsyfbxjc/bigdata/blob/main/code/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [2]:
b = np.arange(6, 12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
np.vstack((a,b))


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
import numpy as np

# 1차원 배열 생성
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 2차원 배열 생성 (vstack/row_stack은 1차원 배열도 2차원으로 변환하여 스택함)
c = np.array([[7, 8, 9]])

print("Using np.vstack():")
# 1차원 배열 a와 b를 수직으로 쌓기 (결과는 2차원 배열이 됨)
result_vstack_1d = np.vstack((a, b))
print(result_vstack_1d)

print("\nUsing np.row_stack():")
# 1차원 배열 a와 b를 수직으로 쌓기 (np.vstack과 동일한 동작)
result_row_stack_1d = np.row_stack((a, b))
print(result_row_stack_1d)

print("\nUsing np.vstack() with 2D array:")
# 2차원 배열 c를 수직으로 쌓기
result_vstack_2d = np.vstack((c, c))
print(result_vstack_2d)

print("\nUsing np.row_stack() with 2D array:")
# 2차원 배열 c를 수직으로 쌓기 (np.vstack과 동일한 동작)
result_row_stack_2d = np.row_stack((c, c))
print(result_row_stack_2d)

# 두 함수의 결과가 동일한지 비교
print(f"\nAre results from vstack and row_stack (1D) identical? {np.array_equal(result_vstack_1d, result_row_stack_1d)}")
print(f"Are results from vstack and row_stack (2D) identical? {np.array_equal(result_vstack_2d, result_row_stack_2d)}")

Using np.vstack():
[[1 2 3]
 [4 5 6]]

Using np.row_stack():
[[1 2 3]
 [4 5 6]]

Using np.vstack() with 2D array:
[[7 8 9]
 [7 8 9]]

Using np.row_stack() with 2D array:
[[7 8 9]
 [7 8 9]]

Are results from vstack and row_stack (1D) identical? True
Are results from vstack and row_stack (2D) identical? True


/tmp/ipykernel_451/2937026887.py:17: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  result_row_stack_1d = np.row_stack((a, b))
/tmp/ipykernel_451/2937026887.py:27: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  result_row_stack_2d = np.row_stack((c, c))


In [5]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [19]:
a = np.arange(1, 13).reshape(3,4)
c = np.arange(1, 7, 2) # c의 요소를 3개로 줄여 a의 행 개수에 맞춤
a,c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 3, 5]))

In [24]:
cc= np.expand_dims(c, axis=1)

In [25]:
np.hstack( (a, cc) )

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [26]:
np.column_stack((a, cc))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [28]:
a = np.arange(1, 4)
b = np.arange(4, 7)
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [29]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
np.c_[a, b], np.column_stack((a, b))

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [33]:
np.c_[(a, b)]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
x = np.arange(1, 4).reshape(1, 3)
y = np.arange(4, 7).reshape(1,3)
x, y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [37]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [38]:
np.c_[x,10, 20,  y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [39]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [126]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
x = np.arange(1, 7).reshape(3, 2)
y = np.arange(7, 13).reshape(3,2)
x,y

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [131]:
m = np.arange(24).reshape(2, 3, 4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [133]:
n = np.arange(96).reshape(4, 4, 6)
n

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]],

       [[72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95]]])

In [ ]:
np.split(n)

# 난수 기초와 생성


In [59]:
import numpy as np

rg = np.random.default_rng(12)
rg.random()

0.2508244581084461

In [82]:
rg.random() * 1

array([0.13435174, 0.76362509, 0.02022872, 0.94560068])

In [81]:
rg.random( (3, 4) )

array([[0.92281088, 0.88025   , 0.0643557 , 0.93669612],
       [0.64924037, 0.87155585, 0.40809847, 0.21938993],
       [0.79297008, 0.66163447, 0.77884009, 0.2013447 ]])

In [86]:
rg.random( (3, 4, 2) )

array([[[0.05725456, 0.72092886],
        [0.77766012, 0.68122731],
        [0.49900353, 0.48551807],
        [0.69466874, 0.24505267]],

       [[0.75258389, 0.19231207],
        [0.03518623, 0.9337309 ],
        [0.09053098, 0.19666771],
        [0.05595927, 0.01023417]],

       [[0.12400543, 0.92134724],
        [0.69552966, 0.4050286 ],
        [0.00658222, 0.82835466],
        [0.4848949 , 0.85380245]]])

In [92]:
import numpy as np
rg = np.random.default_rng(12)
rg.integers(1, 7, (3, 4))

array([[4, 2, 6, 6],
       [1, 2, 2, 2],
       [4, 3, 3, 2]])

In [93]:
rg.integers(1, 10, (2, 8))

array([[9, 7, 6, 2, 2, 9, 3, 8],
       [8, 1, 5, 5, 5, 1, 7, 3]])

In [94]:
rg.integers(low=1, high=10, size=(2, 8))

array([[4, 4, 3, 5, 8, 5, 7, 9],
       [2, 3, 6, 2, 7, 7, 7, 9]])

In [97]:
import numpy as np
rg = np.random.default_rng(12)
rg.standard_normal(10)

array([-0.00682678,  1.04614329,  0.74158842,  0.72395654,  1.61877622,
       -1.20555814, -0.62695547, -1.32066321, -0.10775251,  0.99876366])

In [111]:
rg.standard_normal( (3, 4) )

array([[-1.44604417, -0.2887409 ,  0.34571939,  0.94680771],
       [ 0.67250812,  0.83161998,  1.09713675,  0.82392186],
       [-0.81520341,  0.0580408 , -0.71313858, -2.38147453]])

In [125]:
rg.standard_normal( (10, 5) )

array([[-0.26045893,  1.14337523, -0.3992088 , -0.69042439,  0.00705036],
       [-0.96506941, -0.79268465,  0.64646682, -0.66846606,  1.91748534],
       [ 0.50282083, -0.13717034, -0.65205929, -0.29022387, -2.29822578],
       [ 0.2097744 ,  0.85328093,  0.53756361, -0.46396014,  0.58146183],
       [ 0.60417966, -0.16340264,  0.31649191,  1.00375262,  0.4243168 ],
       [-0.41006818, -0.01929785,  0.12086329, -1.63135395,  0.09883257],
       [-0.1577789 , -2.19318941, -1.737991  ,  1.76701972,  0.07323596],
       [ 1.31348182, -0.4019011 ,  1.50428992,  0.54112409, -0.70927976],
       [ 0.25254811,  1.54106548,  2.36477587,  0.49363211, -0.46578809],
       [-0.8821107 ,  0.66860704,  1.07695533,  0.12849945, -0.11871745]])

# `np.random.random()` vs `np.random.default_rng().random()`

NumPy에는 난수를 생성하는 두 가지 방식이 있습니다. 겉으로는 비슷해 보이지만 내부 동작 방식과 권장 사용 시나리오가 다릅니다.

---

## 1. `np.random.random()` — 레거시 방식

```python
import numpy as np

np.random.seed(42)         # 전역 시드 설정
x = np.random.random(5)    # [0, 1) 범위의 난수 5개 생성
print(x)
```

### 특징
- **전역 상태(Global State)** 기반: 모듈 수준의 단일 난수 생성기를 공유합니다.
- **알고리즘**: Mersenne Twister (MT19937)
- **시드 설정**: `np.random.seed()`로 전역 시드를 설정 — 다른 코드와 충돌 가능성 있음
- **재현성 문제**: 멀티스레드 또는 복잡한 코드에서 시드 관리가 어려움
- **하위 호환성**: NumPy 1.0부터 사용되어 온 오래된 API

> ⚠️ NumPy 공식 문서에서는 새 코드에서는 이 방식을 **권장하지 않습니다.**

---

## 2. `np.random.default_rng().random()` — 새로운 방식 (권장)

```python
import numpy as np

rng = np.random.default_rng(seed=42)  # 독립적인 Generator 객체 생성
x = rng.random(5)                     # [0, 1) 범위의 난수 5개 생성
print(x)
```

### 특징
- **독립적인 Generator 객체**: 전역 상태를 공유하지 않아 다른 코드와 간섭 없음
- **알고리즘**: PCG64 (Permuted Congruential Generator) — MT19937보다 통계적으로 우수
- **시드 설정**: 객체 생성 시 인자로 전달 → 명시적이고 안전
- **재현성 보장**: 객체 단위로 독립 관리되어 멀티스레드 환경에서도 예측 가능
- **더 풍부한 API**: `rng.integers()`, `rng.choice()`, `rng.shuffle()` 등 일관된 인터페이스

---

## 3. 핵심 차이 요약

| 항목 | `np.random.random()` | `np.random.default_rng().random()` |
|------|----------------------|-------------------------------------|
| 도입 시기 | NumPy 초기 (레거시) | NumPy 1.17+ (권장) |
| 상태 관리 | 전역 (모듈 공유) | 독립 객체 |
| 알고리즘 | Mersenne Twister | PCG64 |
| 시드 설정 | `np.random.seed()` | `default_rng(seed=...)` |
| 통계적 품질 | 보통 | 더 우수 |
| 멀티스레드 안전성 | ❌ 불안정 | ✅ 안전 |
| 권장 여부 | ❌ 레거시 | ✅ 신규 코드에 권장 |

---

## 4. 실전 비교 예시

```python
import numpy as np

# --- 레거시 방식 ---
np.random.seed(42)
a = np.random.random(3)

np.random.seed(0)          # 어딘가에서 시드 재설정 → 재현성 깨짐
b = np.random.random(3)

np.random.seed(42)
c = np.random.random(3)    # a와 동일하다고 기대하지만, 중간에 개입 가능

print("a:", a)
print("c:", c)             # a == c (이 예시에서는 같지만, 실제 프로젝트에선 보장 어려움)

# --- 새로운 방식 ---
rng1 = np.random.default_rng(42)
rng2 = np.random.default_rng(42)   # 동일 시드 → 완전히 독립적인 두 객체

print(rng1.random(3))
print(rng2.random(3))              # rng1과 항상 동일한 결과 보장
```

---

## 5. 결론

> **새로 작성하는 코드에서는 항상 `np.random.default_rng()`를 사용하세요.**

- 실험 재현성이 중요한 **머신러닝 / 데이터 과학** 프로젝트
- 여러 모듈이 난수를 사용하는 **대규모 코드베이스**
- **멀티스레드 / 병렬 처리** 환경

위 모든 경우에서 `default_rng()` 방식이 훨씬 안전하고 예측 가능합니다.

레거시 방식(`np.random.random()`)은 간단한 스크립트나 기존 코드 유지보수 시에만 사용하는 것이 좋습니다.